config/routes.rb
Rails.application.routes.draw do
  root "resources#index"
  
  resources :resources

  namespace :api do
    defaults format: :json do
      resources :resources, only: [:create, :show, :index]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/resource.rb
require 'net/http'
require 'uri'

class Resource < ApplicationRecord
  has_one_attached :file
  validates :data, presence: true

  after_commit :enqueue_video_processing, on: :create

  def enqueue_video_processing
    downloads_api = ENV['YOUTUBE_API']
    return unless downloads_api.present?
    return unless data.to_s.match?(/youtube\.com|youtu\.be/)

    url = data.split(/\s+/).find { |string| string.start_with?(/https\:\/\/w{0,3}\.?youtu/) }
    return unless url.present?

    Thread.new do
      Net::HTTP.post(
        URI(downloads_api),
        { 'url' => url }.to_json,
        "Content-Type" => "application/json"
      )
    end
  end
end

app/controllers/api/api_controller.rb
module Api
  class ApiController < ActionController::Base
    include ActiveStorage::SetCurrent

    protect_from_forgery with: :null_session
  end
end

app/controllers/api/resources_controller.rb
module Api
  class ResourcesController < ApiController
    before_action :set_resource, only: %i[ show ]

    # GET /resources
    def index
      resources = Resource.all.order(id: :desc).includes(file_attachment: :blob)
      render json: resources.to_json(include: { file: { only: [], methods: [:url] } })
    end

    def show
      render plain: @resource.data
    end

    def create
      @resource = Resource.new(resource_params)

      if @resource.save
        render plain: "Resource was successfully created, id: #{@resource.id}"
      else
        render plain: @resource.errors.full_messages.join(', ')
      end
    end

    private
      def set_resource
        @resource = Resource.find(params[:id])
      end

      def resource_params
        params.permit(:data, :file)
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ActiveStorage::SetCurrent
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  before_action :set_resource, only: %i[ show edit update destroy ]

  # GET /resources
  def index
    @resources = Resource.all.order(id: :desc)
  end

  # GET /resources/1
  def show
  end

  # GET /resources/new
  def new
    @resource = Resource.new
  end

  # GET /resources/1/edit
  def edit
  end

  # POST /resources
  def create
    @resource = Resource.new(resource_params)

    if @resource.save
      redirect_to @resource, notice: "Resource was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /resources/1
  def update
    if @resource.update(resource_params)
      redirect_to @resource, notice: "Resource was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /resources/1
  def destroy
    @resource.destroy
    redirect_to resources_url, notice: "Resource was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resource
      @resource = Resource.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def resource_params
      params.require(:resource).permit(:data, :file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clippy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/resources/_form.html.erb
<%= form_with(model: resource, class: "contents") do |form| %>
  <% if resource.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
        <% resource.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.text_area :data, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.file_field :file %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/resources/_resource.html.erb
<div id="<%= dom_id resource %>">
  <p class="my-5">
    <%= resource.data %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show", resource, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit', edit_resource_path(resource), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <% if resource.file.attached? %>
      <%= link_to 'Download', rails_blob_path(resource.file, disposition: "attachment"), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <% end %>
    <hr class="mt-6">
  <% end %>

</div>

app/views/resources/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <%= render "form", resource: @resource %>

  <%= link_to "Cancel", @resource, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back", resources_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/resources/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Resources</h1>
    <%= link_to 'Add new', new_resource_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="resources" class="min-w-full">
    <%= render @resources %>
  </div>
</div>

app/views/resources/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New resource</h1>

  <%= render "form", resource: @resource %>

  <%= link_to 'Back to resources', resources_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/resources/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @resource %>

    <% if @resource.file.attached? %>
      <%= link_to 'Download', rails_blob_path(@resource.file, disposition: "attachment"), class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <% end %>
    <%= link_to 'Edit', edit_resource_path(@resource), class: "ml-2 mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy', resource_path(@resource), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back', resources_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>